spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2097152MB
      max-request-size: 2097152MB
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/learning?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zlj@123
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  profiles:
    active: xu



logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
  file: ./log/learning.log

server:
  port: 8080
  context-path: /learning

# 静态文件路径配置
context:
  ctx: /learning
  commonstatic:

login:
  username: admin
  password: admin
  excludes: /,/index,/loginIndex,/error/**
  loginInEntry: /learning/
